/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpmRouteImport } from './routes/spm'
import { Route as SiswaRouteImport } from './routes/siswa'
import { Route as KecamatanRouteImport } from './routes/kecamatan'
import { Route as HambatanRouteImport } from './routes/hambatan'
import { Route as AlatBantuRouteImport } from './routes/alat-bantu'
import { Route as IndexRouteImport } from './routes/index'

const SpmRoute = SpmRouteImport.update({
  id: '/spm',
  path: '/spm',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaRoute = SiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const KecamatanRoute = KecamatanRouteImport.update({
  id: '/kecamatan',
  path: '/kecamatan',
  getParentRoute: () => rootRouteImport,
} as any)
const HambatanRoute = HambatanRouteImport.update({
  id: '/hambatan',
  path: '/hambatan',
  getParentRoute: () => rootRouteImport,
} as any)
const AlatBantuRoute = AlatBantuRouteImport.update({
  id: '/alat-bantu',
  path: '/alat-bantu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alat-bantu': typeof AlatBantuRoute
  '/hambatan': typeof HambatanRoute
  '/kecamatan': typeof KecamatanRoute
  '/siswa': typeof SiswaRoute
  '/spm': typeof SpmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alat-bantu': typeof AlatBantuRoute
  '/hambatan': typeof HambatanRoute
  '/kecamatan': typeof KecamatanRoute
  '/siswa': typeof SiswaRoute
  '/spm': typeof SpmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alat-bantu': typeof AlatBantuRoute
  '/hambatan': typeof HambatanRoute
  '/kecamatan': typeof KecamatanRoute
  '/siswa': typeof SiswaRoute
  '/spm': typeof SpmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alat-bantu'
    | '/hambatan'
    | '/kecamatan'
    | '/siswa'
    | '/spm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alat-bantu' | '/hambatan' | '/kecamatan' | '/siswa' | '/spm'
  id:
    | '__root__'
    | '/'
    | '/alat-bantu'
    | '/hambatan'
    | '/kecamatan'
    | '/siswa'
    | '/spm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlatBantuRoute: typeof AlatBantuRoute
  HambatanRoute: typeof HambatanRoute
  KecamatanRoute: typeof KecamatanRoute
  SiswaRoute: typeof SiswaRoute
  SpmRoute: typeof SpmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spm': {
      id: '/spm'
      path: '/spm'
      fullPath: '/spm'
      preLoaderRoute: typeof SpmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa': {
      id: '/siswa'
      path: '/siswa'
      fullPath: '/siswa'
      preLoaderRoute: typeof SiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kecamatan': {
      id: '/kecamatan'
      path: '/kecamatan'
      fullPath: '/kecamatan'
      preLoaderRoute: typeof KecamatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hambatan': {
      id: '/hambatan'
      path: '/hambatan'
      fullPath: '/hambatan'
      preLoaderRoute: typeof HambatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alat-bantu': {
      id: '/alat-bantu'
      path: '/alat-bantu'
      fullPath: '/alat-bantu'
      preLoaderRoute: typeof AlatBantuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlatBantuRoute: AlatBantuRoute,
  HambatanRoute: HambatanRoute,
  KecamatanRoute: KecamatanRoute,
  SiswaRoute: SiswaRoute,
  SpmRoute: SpmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
